import { test, expect } from '@playwright/test'

async function setup(page, saved = null, denied = false) {
    await page.addInitScript(({ saved, denied }) => {
        if (saved) localStorage.setItem('midivisAppState', JSON.stringify(saved))
        const log = []
        const makePort = id => Object.assign(new EventTarget(), {
            id, name: 'Keyboard', state: 'connected',
            async open() { log.push(`open:${id}`); if (this.wait) await new Promise(resolve => { this.resume = resolve }); if (this.fail) throw new Error('Device connection failed') },
            async close() { log.push(`close:${id}`) },
        })
        const a = makePort('a'), b = makePort('b')
        const access = Object.assign(new EventTarget(), { inputs: new Map([['a', a], ['b', b]]) })
        let requests = 0
        Object.defineProperty(navigator, 'requestMIDIAccess', { value: async () => {
            requests++
            if (denied) throw new DOMException('MIDI permission denied', 'NotAllowedError')
            return access
        } })
        window.fakeMIDI = {
            log,
            requests: () => requests,
            grant() { denied = false },
            pause(id) { access.inputs.get(id).wait = true },
            resume(id) { access.inputs.get(id).resume() },
            add(id, name) {
                const port = makePort(id)
                port.name = name
                access.inputs.set(id, port)
                access.dispatchEvent(new Event('statechange'))
            },
            fail(id) { access.inputs.get(id).fail = true },
            send(id, data) {
                access.inputs.get(id).dispatchEvent(Object.assign(new Event('midimessage'), { data: new Uint8Array(data) }))
            },
            unplug(id) {
                access.inputs.get(id).state = 'disconnected'
                access.dispatchEvent(new Event('statechange'))
            },
        }
    }, { saved, denied })
}
const send = (page, notes) => page.evaluate(notes => {
    for (const note of notes) window.fakeMIDI.send('a', [0x90, note, 100])
}, notes)
const velocity = (page, note) => page.locator('#chordvis').evaluate((element, note) => element.style.getPropertyValue(`--v-max-${note}`), note)

test('connect, play, change settings, transpose held notes and disconnect', async ({ page }) => {
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await setup(page)
    await page.goto('/')
    await expect(page.locator('#config')).toHaveClass(/shown/)
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', 'a')
    await expect.poll(() => page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a'])
    await send(page, [60, 64, 67])
    await expect(page.locator('#chordindicator')).toHaveText('C')
    expect(await velocity(page, 60)).toBe('1')
    await page.evaluate(() => { window.previousKeyboard = document.querySelector('#chordvis > div') })
    await page.click('#settings-tab-ui')
    await page.uncheck('#state-showToolbar')
    expect(await page.evaluate(() => window.previousKeyboard === document.querySelector('#chordvis > div'))).toBe(true)
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-noteArrangement', 'tonnetz')
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-colorCategory', 'circle')
    expect(await page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a'])
    await page.click('#settings-tab-transpose')
    await page.fill('#state-noteOffset', '12')
    await page.locator('#state-noteOffset').dispatchEvent('change')
    expect(await velocity(page, 60)).toBe('0')
    expect(await velocity(page, 72)).toBe('1')
    await page.evaluate(() => window.fakeMIDI.send('a', [0x80, 60, 0]))
    expect(await velocity(page, 72)).toBe('0')
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', '')
    await expect.poll(() => page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a', 'close:a'])
    expect(await velocity(page, 76)).toBe('0')
    expect(errors).toEqual([])
})

test('saved legacy port connects once; unplugging releases held notes', async ({ page }) => {
    await setup(page, { midiInputPortName: 'Keyboard', noteArrangement: 'guitar' })
    await page.goto('/')
    await expect.poll(() => page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a'])
    await expect(page.locator('#state-noteArrangement')).toHaveValue('guitar')
    await send(page, [60])
    await page.evaluate(() => window.fakeMIDI.unplug('a'))
    await expect.poll(() => velocity(page, 60)).toBe('0')
    await expect.poll(() => page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a', 'close:a'])
})

test('permission errors are visible while settings remain usable', async ({ page }) => {
    await setup(page, null, true)
    await page.goto('/')
    await expect(page.locator('#oops')).toHaveClass(/shown/)
    await expect(page.locator('#oops-message')).toContainText('MIDI access was denied')
    await page.click('#oops-close')
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-noteArrangement', 'tonnetz')
    await expect(page.locator('#chordvis .note-bg')).toHaveCount(292)
})

for (const [layout, count] of [['fourth', 276], ['tonnetz', 292], ['janko-slanted', 1020]]) {
    test(`${layout} geometry and visual review`, async ({ page }, testInfo) => {
        await setup(page, { midiInputPortName: 'a', noteArrangement: layout, colorScheme: 'fifth' })
        await page.goto('/')
        await expect(page.locator('#chordvis .note-bg')).toHaveCount(count)
        await send(page, [60, 64, 67])
        await expect(page.locator('#chordindicator')).toHaveText('C')
        const cell = page.locator('#chordvis .note-bg:visible').first()
        expect((await cell.boundingBox()).width).toBeGreaterThan(0)
        if (layout === 'janko-slanted') {
            await expect(page.locator('#chordvis > div')).not.toHaveCSS('transform', 'none')
            expect(await page.locator('#chordvis .note-bg').evaluateAll(cells => cells.some(cell => getComputedStyle(cell).visibility === 'hidden'))).toBe(true)
        }
        await page.screenshot({ path: testInfo.outputPath(`${layout}.png`), fullPage: true })
    })
}

test('license page still includes bundled license text', async ({ page }) => {
    await page.goto('/about.html')
    await expect(page.locator('#licenses')).toContainText('Permission is hereby granted')
    await expect(page.locator('#licenses')).toContainText('Node.js License')
})

test('settings close with Escape, leave tab order, and remain reachable without toolbar', async ({ page }) => {
    await setup(page)
    await page.goto('/')
    await expect(page.locator('#config-close')).toBeFocused()
    await expect(page.locator('#menu-settings')).toHaveAttribute('aria-expanded', 'true')
    await page.keyboard.press('Escape')
    await expect(page.locator('#config')).toBeHidden()
    await expect(page.locator('#menu-settings')).toBeFocused()
    await page.keyboard.press('Tab')
    expect(await page.evaluate(() => document.getElementById('config').contains(document.activeElement))).toBe(false)
    await page.click('#menu-settings')
    await page.click('#settings-tab-ui')
    await page.uncheck('#state-showToolbar')
    await page.click('#config-close')
    await expect(page.locator('#menu-settings')).toBeVisible()
    await expect(page.locator('#menu-settings')).toBeFocused()
    await page.click('#menu-settings')
    await expect(page.locator('#config-close')).toBeFocused()
    await page.reload()
    await expect(page.locator('#toolbar')).toBeHidden()
    await expect(page.locator('#menu-settings')).toBeVisible()
})

test('chord names update immediately and invalid transpose keeps the saved setting', async ({ page }) => {
    await setup(page)
    await page.goto('/')
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', 'a')
    await expect(page.locator('#midi-status')).toContainText('Connected:')
    await send(page, [62, 66, 69])
    await expect(page.locator('#chordindicator')).toHaveText('D')
    await page.click('#settings-tab-chords')
    await page.check('#state-useDegree')
    await expect(page.locator('#chordindicator')).toHaveText('II')
    await page.click('#settings-tab-chords')
    await page.selectOption('#state-key', '2')
    await expect(page.locator('#chordindicator')).toHaveText('I')
    await page.click('#settings-tab-transpose')
    const offset = page.locator('#state-noteOffset')
    await offset.fill('12')
    await offset.dispatchEvent('change')
    expect(await velocity(page, 74)).toBe('1')
    await offset.fill('25')
    await offset.dispatchEvent('change')
    await expect(offset).toHaveValue('25')
    await expect(offset).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('#offset-error')).toBeVisible()
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('midivisAppState')).noteOffsets[0])).toBe(12)
    expect(await velocity(page, 74)).toBe('1')
    await page.click('#config-close')
    await page.click('#menu-settings')
    await expect(offset).toHaveValue('12')
    await expect(page.locator('#offset-error')).toBeHidden()
    await offset.fill('-1')
    await offset.dispatchEvent('change')
    await expect(page.locator('#chordindicator')).toHaveText('VII')
})

test('port discovery, unplugging and failed selection show actual connection state', async ({ page }) => {
    await setup(page)
    await page.goto('/')
    await expect(page.locator('#config-midi-input-port option[value="a"]')).toHaveText('Keyboard (a)')
    await expect(page.locator('#config-midi-input-port option[value="b"]')).toHaveText('Keyboard (b)')
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', 'a')
    await expect(page.locator('#midi-status')).toContainText('Connected:')
    await page.evaluate(() => window.fakeMIDI.add('c', 'New input'))
    await expect(page.locator('#config-midi-input-port option[value="c"]')).toHaveCount(1)
    await page.evaluate(() => window.fakeMIDI.unplug('a'))
    await expect(page.locator('#config-midi-input-port')).toHaveValue('')
    await expect(page.locator('#midi-status')).toContainText('Not connected')
    await page.evaluate(() => window.fakeMIDI.fail('b'))
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', 'b')
    await expect(page.locator('#oops-message')).toContainText('The MIDI device could not be opened or closed')
    await expect(page.locator('#config-midi-input-port')).toHaveValue('')
    await expect(page.locator('#midi-status')).toContainText('Not connected')
    await expect(page.locator('#oops')).not.toContainText('Firefox 98')
    await page.click('#oops-close')
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', 'c')
    await expect(page.locator('#midi-status')).toHaveText('Connected: New input')
})

for (const viewport of [{ width: 1280, height: 800 }, { width: 375, height: 667 }]) {
    test(`settings fit ${viewport.width}px including long device names`, async ({ page }, testInfo) => {
        await page.setViewportSize(viewport)
        await setup(page)
        await page.goto('/')
        await page.evaluate(() => window.fakeMIDI.add('long', 'A very long USB MIDI controller input port name - MIDI 1 - USB connection'))
        await expect(page.locator('#config-midi-input-port option[value="long"]')).toHaveCount(1)
        await page.click('#settings-tab-connection')
        await page.selectOption('#config-midi-input-port', 'long')
        await expect(page.locator('#midi-status')).toContainText('Connected:')
        for (const selector of ['#config', '#config-close', '#config-midi-input-port']) {
            const box = await page.locator(selector).boundingBox()
            expect(box.x).toBeGreaterThanOrEqual(0)
            expect(box.x + box.width).toBeLessThanOrEqual(viewport.width)
        }
        const closeBox = await page.locator('#config-close').boundingBox()
        expect(closeBox.y + closeBox.height).toBeLessThan(viewport.height)
        await expect(page.getByLabel('Layout', { exact: true })).toHaveCount(1)
        await page.locator('.settings-content').evaluate(element => { element.scrollTop = element.scrollHeight })
        await expect(page.locator('#config-close')).toBeInViewport()
        await page.locator('.settings-content').evaluate(element => { element.scrollTop = 0 })
        await page.screenshot({ path: testInfo.outputPath('settings.png') })
    })
}

test('connection progress is visible and device selection waits for completion', async ({ page }) => {
    await setup(page)
    await page.goto('/')
    await page.evaluate(() => window.fakeMIDI.pause('a'))
    await page.click('#settings-tab-connection')
    await page.selectOption('#config-midi-input-port', 'a')
    await expect(page.locator('#midi-status')).toHaveText('Connecting…')
    await expect(page.locator('#config-midi-input-port')).toBeDisabled()
    await expect(page.locator('#midi-refresh')).toBeDisabled()
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-noteArrangement', 'guitar')
    await page.evaluate(() => window.fakeMIDI.resume('a'))
    await expect(page.locator('#midi-status')).toHaveText('Connected: Keyboard')
    await expect(page.locator('#config-midi-input-port')).toBeEnabled()
})

test('refresh recovers from denied permissions and explains an empty input list', async ({ page }) => {
    await setup(page, null, true)
    await page.goto('/')
    await expect(page.locator('#oops')).toBeVisible()
    await page.click('#oops-close')
    await page.evaluate(() => window.fakeMIDI.grant())
    await page.click('#midi-refresh')
    await expect(page.locator('#config-midi-input-port option')).toHaveCount(3)
    await expect(page.locator('#oops')).toBeHidden()
    await page.evaluate(() => { window.fakeMIDI.unplug('a'); window.fakeMIDI.unplug('b') })
    await expect(page.locator('#midi-status')).toContainText('No MIDI inputs found')
    await expect(page.locator('#config-midi-input-port option')).toHaveCount(1)
})


test('a denied saved connection does not automatically request permission again', async ({ page }) => {
    await setup(page, { midiInputPortName: 'a' }, true)
    await page.goto('/')
    await expect(page.locator('#oops')).toBeVisible()
    expect(await page.evaluate(() => window.fakeMIDI.requests())).toBe(1)
    await page.click('#oops-close')
    await page.evaluate(() => window.fakeMIDI.grant())
    await page.click('#midi-refresh')
    await expect(page.locator('#config-midi-input-port option')).toHaveCount(3)
    expect(await page.evaluate(() => window.fakeMIDI.requests())).toBe(2)
})

test('vertical tabs expose one category and support arrow, Home, End and Tab keys', async ({ page }) => {
    await setup(page)
    await page.goto('/')
    const tabs = page.getByRole('tab')
    await expect(page.getByRole('tablist')).toHaveAttribute('aria-orientation', 'vertical')
    await expect(tabs).toHaveText(['UI', 'Connection', 'Transpose', 'Visuals', 'Chords'])
    await expect(page.getByRole('tabpanel')).toHaveCount(1)
    await page.getByRole('tab', { name: 'Connection', exact: true }).focus()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('tab', { name: 'Transpose', exact: true })).toBeFocused()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('tab', { name: 'Visuals', exact: true })).toBeFocused()
    await expect(page.getByRole('tab', { name: 'Visuals', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByLabel('Layout', { exact: true })).toBeVisible()
    await expect(page.locator('#config-midi-input-port')).toBeHidden()
    await page.keyboard.press('Tab')
    await expect(page.locator('#state-noteArrangement')).toBeFocused()
    await page.selectOption('#state-noteArrangement', 'guitar')
    await page.getByRole('tab', { name: 'Visuals', exact: true }).focus()
    await page.keyboard.press('End')
    await expect(page.getByRole('tab', { name: 'Chords', exact: true })).toBeFocused()
    await page.keyboard.press('ArrowDown')
    await expect(page.getByRole('tab', { name: 'UI', exact: true })).toBeFocused()
    await page.keyboard.press('ArrowUp')
    await expect(page.getByRole('tab', { name: 'Chords', exact: true })).toBeFocused()
    await page.keyboard.press('Home')
    await expect(page.getByRole('tab', { name: 'UI', exact: true })).toBeFocused()
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement')).toHaveValue('guitar')
    await page.click('#config-close')
    await page.click('#menu-settings')
    await expect(page.getByRole('tab', { name: 'Visuals', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.locator('#state-noteArrangement')).toHaveValue('guitar')
    expect(await page.evaluate(() => window.fakeMIDI.log)).toEqual([])
})

for (const width of [1280, 375]) {
    test(`all vertical tab categories fit ${width}px`, async ({ page }, testInfo) => {
        await page.setViewportSize({ width, height: 800 })
        await setup(page)
        await page.goto('/')
        for (const id of ['connection', 'visualization', 'ui', 'chords', 'transpose']) {
            await page.click(`#settings-tab-${id}`)
            await expect(page.getByRole('tabpanel')).toHaveCount(1)
            const overflow = await page.locator('.settings-content').evaluate(element => element.scrollWidth > element.clientWidth)
            expect(overflow).toBe(false)
            await expect(page.locator('#config-close')).toBeInViewport()
            await page.screenshot({ path: testInfo.outputPath(`${id}.png`) })
        }
    })
}

test.describe('Japanese UI', () => {
    test.use({ locale: 'ja-JP' })

    test('detects browser language, switches live and persists the explicit choice', async ({ page, context }) => {
        await setup(page)
        await page.goto('/')
        await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
        await expect(page.getByRole('button', { name: '設定を閉じる', exact: true })).toBeVisible()
        await expect(page.getByRole('tab', { name: '接続', exact: true })).toBeVisible()
        await page.selectOption('#config-midi-input-port', 'a')
        await expect(page.locator('#midi-status')).toHaveText('接続中：Keyboard')
        await page.click('#settings-tab-transpose')
        await page.fill('#state-noteOffset', '25')
        await page.locator('#state-noteOffset').dispatchEvent('change')
        await expect(page.locator('#offset-error')).toContainText('整数を入力')
        await page.click('#settings-tab-visualization')
        await expect(page.locator('#state-noteArrangement option[value="guitar"]')).toHaveText('ギター')
        await page.evaluate(() => { window.keyboardBeforeLanguage = document.querySelector('#chordvis > div') })
        await page.click('#settings-tab-ui')
        await page.locator('#state-language').focus()
        await page.selectOption('#state-language', 'en')
        await expect(page.locator('#state-language')).toBeFocused()
        await expect(page.locator('html')).toHaveAttribute('lang', 'en')
        await expect(page.getByRole('tab', { name: 'UI', exact: true })).toHaveAttribute('aria-selected', 'true')
        await expect(page.locator('#midi-status')).toHaveText('Connected: Keyboard')
        expect(await page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a'])
        expect(await page.evaluate(() => document.querySelector('#chordvis > div') === window.keyboardBeforeLanguage)).toBe(true)
        await page.click('#settings-tab-transpose')
        await expect(page.locator('#state-noteOffset')).toHaveValue('25')
        await expect(page.locator('#offset-error')).toContainText('Enter a whole number')
        await page.reload()
        await expect(page.locator('html')).toHaveAttribute('lang', 'en')
        const about = await context.newPage()
        await about.goto('/about.html')
        await expect(about).toHaveTitle('About Midivis')
        await page.click('#menu-settings')
        await page.click('#settings-tab-ui')
        await page.selectOption('#state-language', 'auto')
        await expect(page.locator('html')).toHaveAttribute('lang', 'ja')
        await expect(about).toHaveTitle('Midivisについて')
        await expect(about.locator('#licenses')).toContainText('Permission is hereby granted')
        await about.close()
    })

    test('translates errors again when the language changes', async ({ page }) => {
        await setup(page, null, true)
        await page.goto('/')
        await expect(page.locator('#oops-message')).toContainText('アクセスが拒否されました')
        await page.click('#settings-tab-ui')
        await page.selectOption('#state-language', 'en')
        await expect(page.locator('#oops-message')).toContainText('MIDI access was denied')
        await expect(page.locator('#midi-status')).toContainText('MIDI inputs unavailable')
    })

    test('translated categories fit a narrow screen', async ({ page }, testInfo) => {
        await page.setViewportSize({ width: 375, height: 667 })
        await setup(page)
        await page.goto('/')
        for (const id of ['connection', 'visualization', 'ui', 'chords', 'transpose']) {
            await page.click(`#settings-tab-${id}`)
            expect(await page.locator('.settings-content').evaluate(element => element.scrollWidth > element.clientWidth)).toBe(false)
            await expect(page.locator('#config-close')).toBeInViewport()
            await page.screenshot({ path: testInfo.outputPath(`${id}-ja.png`) })
        }
    })
})

test.describe('Unsupported browser locale', () => {
    test.use({ locale: 'de-DE' })
    test('falls back to English', async ({ page }) => {
        await setup(page)
        await page.goto('/')
        await expect(page.locator('html')).toHaveAttribute('lang', 'en')
        await expect(page.locator('#config-title')).toHaveText('Settings')
    })
})

for (const [scheme, category] of [
    ['monotone', 'monotone'], ['chromatic', 'interval'], ['fifth', 'circle'],
    ['axis', 'circle'], ['quintave', 'interval'], ['third-major', 'interval'],
]) {
    test(`saved color ${scheme} restores its category and detail`, async ({ page }) => {
        await setup(page, { colorScheme: scheme })
        await page.goto('/')
        await page.click('#settings-tab-visualization')
        await expect(page.locator('#state-colorCategory')).toHaveValue(category)
        await expect(page.locator('#state-colorScheme')).toHaveValue(scheme)
        await expect(page.locator('#color-detail')).toBeVisible({ visible: category !== 'monotone' })
    })
}

test('color categories, shortcuts, language and saved state stay synchronized', async ({ page }) => {
    await setup(page)
    await page.setViewportSize({ width: 320, height: 640 })
    await page.goto('/')
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-colorCategory', 'interval')
    await expect(page.locator('#state-colorScheme option')).toHaveCount(3)
    await expect(page.locator('#state-colorScheme')).toHaveValue('chromatic')
    await page.selectOption('#state-colorScheme', 'quintave')
    await page.click('#settings-tab-ui')
    await page.selectOption('#state-language', 'ja')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#color-detail-label')).toHaveText('色相の周期')
    await expect(page.locator('#state-colorScheme option:checked')).toHaveText('7半音（完全五度）')
    await page.keyboard.press('Alt+4')
    await expect(page.locator('#state-colorCategory')).toHaveValue('circle')
    await expect(page.locator('#state-colorScheme')).toHaveValue('axis')
    await expect(page.locator('#color-detail-label')).toHaveText('配色方式')
    await expect(page.locator('#color-help')).toContainText('中心軸')
    await page.click('#settings-tab-ui')
    await page.selectOption('#state-language', 'en')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-colorScheme option:checked')).toHaveText('Axis system')
    await page.keyboard.press('Alt+6')
    await expect(page.locator('#state-colorCategory')).toHaveValue('interval')
    await expect(page.locator('#state-colorScheme')).toHaveValue('third-major')
    await page.reload()
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-colorScheme')).toHaveValue('third-major')
    await page.click('#settings-tab-ui')
    await page.selectOption('#state-language', 'ja')
    await page.click('#settings-tab-visualization')
    expect(await page.locator('.settings-content').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.screenshot({ path: test.info().outputPath('color-settings-ja.png') })
    await page.keyboard.press('Alt+1')
    await expect(page.locator('#state-colorCategory')).toHaveValue('monotone')
    await expect(page.locator('#color-detail')).toBeHidden()
})

test('grouped layouts and variants persist and translate without reconnecting MIDI', async ({ page }) => {
    await setup(page)
    await page.setViewportSize({ width: 375, height: 740 })
    await page.goto('/')
    await page.selectOption('#config-midi-input-port', 'a')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement optgroup')).toHaveCount(4)
    await expect(page.locator('#state-noteArrangement option')).toHaveCount(15)
    await page.selectOption('#state-noteArrangement', 'wicki-hayden')
    await expect(page.locator('#state-arrangementVariant option')).toHaveCount(2)
    await page.selectOption('#state-arrangementVariant', 'wicki-hayden-wide')
    await page.selectOption('#state-noteArrangement', 'janko')
    await expect(page.locator('#state-arrangementVariant option')).toHaveCount(3)
    await page.selectOption('#state-arrangementVariant', 'janko-slanted')
    await page.evaluate(() => { window.previousKeyboard = document.querySelector('#chordvis > div') })
    await page.click('#settings-tab-ui')
    await page.selectOption('#state-language', 'ja')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement optgroup').nth(2)).toHaveAttribute('label', '鍵盤・ボタン配列')
    await expect(page.locator('#state-arrangementVariant option:checked')).toHaveText('斜め')
    expect(await page.evaluate(() => window.previousKeyboard === document.querySelector('#chordvis > div'))).toBe(true)
    expect(await page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a'])
    await page.screenshot({ path: test.info().outputPath('layout-settings-ja.png') })
    expect(await page.locator('.settings-content').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.reload()
    await page.click('#menu-settings')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement')).toHaveValue('janko')
    await expect(page.locator('#state-arrangementVariant')).toHaveValue('janko-slanted')
    await page.selectOption('#state-noteArrangement', 'guitar')
    await expect(page.locator('#arrangement-detail')).toBeHidden()
    await expect(page.locator('#arrangement-help')).toContainText('6弦ギターの標準調弦')
    await page.click('#settings-tab-ui')
    await page.selectOption('#state-language', 'en')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement optgroup').nth(3)).toHaveAttribute('label', 'String instrument fretboards')
    await expect(page.locator('#arrangement-help')).toContainText('six-string guitar')
})

test('octave folding lights every C, hides numbers and persists', async ({ page }) => {
    await setup(page)
    await page.goto('/')
    await page.selectOption('#config-midi-input-port', 'a')
    await send(page, [60])
    await page.click('#settings-tab-visualization')
    await page.check('#state-ignoreOctave')
    await expect(page.locator('#chordvis sub')).toHaveCount(0)
    expect(await velocity(page, 0)).toBe('1')
    const cCells = page.locator('.note-fg').filter({ hasText: /^C$/ })
    expect(await cCells.count()).toBeGreaterThan(2)
    expect(await cCells.evaluateAll(cells => cells.every(cell => getComputedStyle(cell).color === 'rgb(0, 0, 0)'))).toBe(true)
    await page.evaluate(() => window.fakeMIDI.send('a', [0x91, 72, 100]))
    await page.evaluate(() => window.fakeMIDI.send('a', [0x80, 60, 0]))
    expect(await velocity(page, 0)).toBe('1')
    await page.uncheck('#state-ignoreOctave')
    expect(await velocity(page, 72)).toBe('1')
    expect(await velocity(page, 60)).toBe('0')
    await expect(page.locator('#chordvis sub').first()).toBeAttached()
    await page.check('#state-ignoreOctave')
    expect(await page.evaluate(() => window.fakeMIDI.log)).toEqual(['open:a'])
    await page.reload()
    await page.click('#menu-settings')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-ignoreOctave')).toBeChecked()
    await expect(page.locator('#chordvis sub')).toHaveCount(0)
})

test('piano octave directions, black keys, folding and persistence', async ({ page }) => {
    await setup(page)
    await page.setViewportSize({ width: 1280, height: 1100 })
    await page.goto('/')
    await page.selectOption('#config-midi-input-port', 'a')
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-noteArrangement', 'piano')
    await expect(page.locator('#arrangement-variant-label')).toHaveText('Octave direction')
    await expect(page.locator('#state-arrangementVariant')).toHaveValue('piano')
    await expect(page.locator('.piano-white')).toHaveCount(52)
    await expect(page.locator('.piano-black')).toHaveCount(36)
    const key = note => page.locator(`.note-bg[data-note="${note}"]`)
    let c4 = await key(60).boundingBox(), c5 = await key(72).boundingBox()
    expect(c5.x - c4.x).toBe(280)
    expect(c5.y).toBe(c4.y)
    await send(page, [60, 61, 64, 67])
    expect(await velocity(page, 61)).toBe('1')
    await page.selectOption('#state-arrangementVariant', 'piano-vertical')
    c4 = await key(60).boundingBox(); c5 = await key(72).boundingBox()
    expect(c5.x).toBe(c4.x)
    expect(c4.y - c5.y).toBe(112)
    expect(await velocity(page, 61)).toBe('1')
    await page.click('#config-close')
    await page.screenshot({ path: test.info().outputPath('piano-vertical.png') })
    await page.click('#menu-settings')
    await page.check('#state-ignoreOctave')
    await expect(page.locator('#chordvis sub')).toHaveCount(0)
    expect(await velocity(page, 1)).toBe('1')
    await page.evaluate(() => window.fakeMIDI.send('a', [0x80, 61, 0]))
    expect(await velocity(page, 1)).toBe('0')
    await page.reload()
    await page.click('#menu-settings')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement')).toHaveValue('piano')
    await expect(page.locator('#state-arrangementVariant')).toHaveValue('piano-vertical')
    await page.selectOption('#state-arrangementVariant', 'piano')
    await page.setViewportSize({ width: 2200, height: 420 })
    await page.click('#config-close')
    await page.screenshot({ path: test.info().outputPath('piano-horizontal.png') })
})

for (const [layout, interval] of [['fourth-whole-tone', 'fourth'], ['fifth-whole-tone', 'fifth']]) test(`${layout} plays and restores its saved selection`, async ({ page }) => {
    await setup(page)
    await page.goto('/')
    await page.selectOption('#config-midi-input-port', 'a')
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-noteArrangement', layout)
    await expect(page.locator('#arrangement-help')).toHaveText(`Whole tones run horizontally, with a perfect ${interval} between rows.`)
    await expect(page.locator('#arrangement-detail')).toBeHidden()
    await expect(page.locator('.note-fg')).toHaveCount(276)
    await send(page, [60, 62, 65])
    for (const note of [60, 62, 65]) expect(await velocity(page, note)).toBe('1')
    await page.evaluate(() => window.fakeMIDI.send('a', [0x80, 62, 0]))
    expect(await velocity(page, 62)).toBe('0')
    await page.reload()
    await page.click('#menu-settings')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-noteArrangement')).toHaveValue(layout)
})

test('channel coloring renders bands, translates the setting and persists', async ({ page }) => {
    await setup(page)
    await page.setViewportSize({ width: 375, height: 800 })
    await page.goto('/')
    await page.selectOption('#config-midi-input-port', 'a')
    await page.click('#settings-tab-visualization')
    await page.selectOption('#state-colorCategory', 'channel')
    await expect(page.locator('#color-detail')).toBeHidden()
    await expect(page.locator('#channel-colors li')).toHaveCount(15)
    await send(page, [60])
    const c4 = page.locator('.note-fg').filter({ hasText: /^C4$/ }).first()
    const background = () => c4.evaluate(el => getComputedStyle(el).backgroundImage)
    const solo = await background()
    expect(solo).toContain('linear-gradient')
    await page.evaluate(() => window.fakeMIDI.send('a', [0x91, 60, 100]))
    const duet = await background()
    expect(duet).not.toBe(solo)
    expect(duet).toContain('50%')
    await page.evaluate(() => window.fakeMIDI.send('a', [0x81, 60, 0]))
    expect(await background()).toBe(solo)
    await page.check('#state-ignoreOctave')
    await page.evaluate(() => window.fakeMIDI.send('a', [0x91, 72, 100]))
    const allC = page.locator('.note-fg').filter({ hasText: /^C$/ })
    const fills = await allC.evaluateAll(cells => cells.map(el => getComputedStyle(el).backgroundImage))
    expect(new Set(fills).size).toBe(1)
    expect(fills[0]).toContain('50%')
    await page.click('#settings-tab-ui')
    await page.selectOption('#state-language', 'ja')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-colorCategory option:checked')).toHaveText('MIDIチャンネル')
    await expect(page.locator('#color-help')).toContainText('色の帯')
    expect(await page.locator('.settings-content').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.screenshot({ path: test.info().outputPath('channel-settings-ja.png') })
    await page.reload()
    await page.click('#menu-settings')
    await page.click('#settings-tab-visualization')
    await expect(page.locator('#state-colorCategory')).toHaveValue('channel')
    await page.keyboard.press('Alt+1')
    await expect(page.locator('#channel-colors')).toBeHidden()
    await page.keyboard.press('Alt+7')
    await expect(page.locator('#channel-colors')).toBeVisible()
})
