type NoteArrangement =
  | "third"
  | "fourth"
  | "tritone"
  | "fifth"
  | "octave"
  | "c-system"
  | "b-system"
  | "wicki-hayden"
  | "wicki-hayden-wide"
  | "tonnetz"
  | "janko"
  | "janko-tall"
  | "janko-slanted"
  | "guitar"
  | "bass"

type ColorScheme =
  | "monotone"
  | "chromatic"
  | "fifth"
  | "axis"
  | "quintave"
  | "third-major"
